version: '3'

services:
  postgres1:
    image: postgres:latest
    container_name: dummbatz_postgres1
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "6660:5432"

  postgres2:
    image: postgres:latest
    container_name: dummbatz_postgres2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "7770:5432"